//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationPoint.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodStorage
    {
        public int ID { get; set; }
        public int ID_Donor { get; set; }
        public string Component { get; set; }
        public System.DateTime Date_Sbora { get; set; }
        public string Group { get; set; }
        public string Rh { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
