//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationPoint.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Patients = new HashSet<Patients>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Fatherhood { get; set; }
        public Nullable<int> Stage { get; set; }
        public bool Vacation { get; set; }
        public int Number_of_patients { get; set; }
        public int Maximum_number_of_patients { get; set; }
        public string MainImagePath { get; set; }
        public int ID_Manager { get; set; }

        public string ActualVacation
        {
            get
            {
                return Vacation ? "В отпуске" : "Не в отпуске";
            }
        }
    
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients> Patients { get; set; }
    }
}
